import csv
from pprint import pprint

place_types = {
    "3D printing service": "Service",
    "Abbey": "Place of Worship",
    "Academic department": "Educational Institution",
    "Açaí shop": "Food & Drink",
    "Accountant": "Professional Services",
    "Accounting firm": "Professional Services",
    "Acoustical consultant": "Consulting",
    "Acupuncture clinic": "Doctors",
    "Acupuncturist": "Doctors",
    "Acura dealer": "Automotive",
    "Adaptive sports center": "Sports & Recreation",
    "Addiction treatment center": "Doctors",
    "Administrative attorney": "Legal Services",
    "Adoption agency": "Social Services",
    "Adult day care center": "Doctors",
    "Adult education school": "Educational Institution",
    "Adult entertainment club": "Entertainment",
    "Adventure sports center": "Sports & Recreation",
    "Advertising": "Marketing",
    "Advertising agency": "Marketing",
    "Advertising service": "Marketing",
    "Aerial photographer": "Service",
    "Aerial sports center": "Sports & Recreation",
    "Aerobics instructor": "Fitness & Wellness",
    "Aeroclub": "Sports & Recreation",
    "Aeronautical engineer": "Professional Services",
    "Aerospace company": "Industry",
    "African restaurant": "Food & Drink",
    "After school program": "Educational Institution",
    "Aged care": "Doctors",
    "Aggregate supplier": "Industry",
    "Agricultural association": "Organization",
    "Agricultural cooperative": "Organization",
    "Agricultural engineer": "Professional Services",
    "Agricultural machinery manufacturer": "Industry",
    "Agricultural organization": "Organization",
    "Agricultural production": "Industry",
    "Agricultural service": "Service",
    "Agriculture": "Industry",
    "Agrochemicals supplier": "Industry",
    "Aikido school": "Sports & Recreation",
    "Air compressor supplier": "Retail",
    "Air conditioning contractor": "Service",
    "Air conditioning repair service": "Service",
    "Air conditioning system supplier": "Retail",
    "Air duct cleaning service": "Service",
    "Air filter supplier": "Retail",
    "Air force base": "Military",
    "Air taxi": "Transportation",
    "Aircraft dealer": "Transportation",
    "Aircraft maintenance company": "Transportation",
    "Aircraft manufacturer": "Industry",
    "Aircraft rental service": "Transportation",
    "Aircraft supply store": "Retail",
    "Airline": "Transportation",
    "Airline ticket agency": "Travel & Transport",
    "Airplane": "Transportation",
    "Airport": "Transportation",
    "Airport parking lot": "Transportation",
    "Airport shuttle service": "Transportation",
    "Airsoft supply store": "Retail",
    "Airstrip": "Transportation",
    "Alcoholic beverage wholesaler": "Retail",
    "Allergist": "Doctors",
    "Alternative medicine": "Doctors",
    "Alternative medicine practitioner": "Doctors",
    "Aluminum supplier": "Industry",
    "Aluminum welder": "Service",
    "Ambulance service": "Doctors",
    "American football field": "Sports & Recreation",
    "American restaurant": "Food & Drink",
    "Ammunition supplier": "Retail",
    "Amphitheater": "Entertainment",
    "Amusement center": "Entertainment",
    "Amusement park": "Entertainment",
    "Amusement park ride": "Entertainment",
    "Anesthesiologist": "Doctors",
    "Animal control service": "Service",
    "Animal feed store": "Retail",
    "Animal hospital": "Doctors",
    "Animal protection organization": "Organization",
    "Animal rescue service": "Service",
    "Animal shelter": "Doctors",
    "Animals": "Category",
    "Animation studio": "Entertainment",
    "Antenna service": "Service",
    "Antique furniture store": "Retail",
    "Antique store": "Retail",
    "Apartment building": "Residential",
    "Apartment complex": "Residential",
    "Apartment rental agency": "Real Estate",
    "Apostolic church": "Place of Worship",
    "Apparel company": "Retail",
    "Appliance parts supplier": "Retail",
    "Appliance repair service": "Service",
    "Appliance store": "Retail",
    "Appraiser": "Professional Services",
    "Aquarium": "Entertainment",
    "Aquatic centre": "Sports & Recreation",
    "Arboretum": "Outdoor",
    "Arborist service": "Service",
    "Archaeological museum": "Museum",
    "Archaeological site": "Tourist Attraction",
    "Archery store": "Retail",
    "Architect": "Professional Services",
    "Architects association": "Organization",
    "Architectural and engineering model maker": "Industry",
    "Architectural designer": "Professional Services",
    "Architectural salvage store": "Retail",
    "Architecture": "Industry",
    "Architecture firm": "Professional Services",
    "Architecture school": "Educational Institution",
    "Arena": "Entertainment",
    "Argentinian restaurant": "Food & Drink",
    "Armed forces association": "Organization",
    "Army & navy surplus shop": "Retail",
    "Army facility": "Military",
    "Army museum": "Museum",
    "Aromatherapy service": "Doctors",
    "Art center": "Arts & Culture",
    "Art gallery": "Arts & Culture",
    "Art museum": "Museum",
    "Art school": "Educational Institution",
    "Art studio": "Arts & Culture",
    "Art supply store": "Retail",
    "Artificial plant supplier": "Retail",
    "Artist": "Arts & Culture",
    "Artistic handicrafts": "Arts & Culture",
    "Arts organization": "Organization",
    "Asbestos testing service": "Service",
    "Asian fusion restaurant": "Food & Drink",
    "Asian grocery store": "Retail",
    "Asian household goods store": "Retail",
    "Asian restaurant": "Food & Drink",
    "Asphalt contractor": "Service",
    "Asphalt mixing plant": "Industry",
    "Assemblies of God church": "Place of Worship",
    "Assembly hall": "Entertainment",
    "Assisted living facility": "Doctors",
    "Association / Organization": "Organization",
    "Astrologer": "Consulting",
    "Athletic club": "Sports & Recreation",
    "Athletic field": "Sports & Recreation",
    "Athletic track": "Sports & Recreation",
    "ATM": "Service",
    "Attorney": "Legal Services",
    "Attorney referral service": "Legal Services",
    "ATV dealer": "Retail",
    "ATV rental service": "Service",
    "ATV repair shop": "Service",
    "Auction house": "Retail",
    "Audi dealer": "Automotive",
    "Audio visual consultant": "Consulting",
    "Audio visual equipment repair service": "Service",
    "Audio visual equipment supplier": "Retail",
    "Audiologist": "Doctors",
    "Audiovisual equipment rental service": "Service",
    "Auditor": "Professional Services",
    "Auditorium": "Entertainment",
    "Authentic Japanese restaurant": "Food & Drink",
    "Auto accessories wholesaler": "Retail",
    "Auto auction": "Automotive",
    "Auto body parts supplier": "Retail",
    "Auto body shop": "Automotive",
    "Auto bodywork mechanic": "Service",
    "Auto broker": "Automotive",
    "Auto dent removal service": "Service",
    "Auto glass repair service": "Service",
    "Auto glass shop": "Retail",
    "Auto insurance agency": "Insurance",
    "Auto machine shop": "Automotive",
    "Auto parts manufacturer": "Industry",
    "Auto parts market": "Retail",
    "Auto parts store": "Retail",
    "Auto repair shop": "Service",
    "Auto restoration service": "Service",
    "Auto tune up service": "Service",
    "Auto upholsterer": "Service",
    "Auto window tinting service": "Service",
    "Auto wrecker": "Automotive",
    "Automation company": "Industry",
    "Automobile storage facility": "Service",
    "Automotive": "Industry",
    "Aviation": "Transportation",
    "Aviation consultant": "Consulting",
    "Aviation training institute": "Educational Institution",
    "Awning supplier": "Retail",
    "Ayurvedic clinic": "Doctors",
    "Baby store": "Retail",
    "Badminton club": "Sports & Recreation",
    "Bag shop": "Retail",
    "Bagel shop": "Food & Drink",
    "Bail bonds service": "Legal Services",
    "Bait shop": "Retail",
    "Bakery": "Food & Drink",
    "Ballet school": "Educational Institution",
    "Balloon artist": "Service",
    "Balloon ride tour agency": "Tourism",
    "Ballroom dance instructor": "Service",
    "Band": "Entertainment",
"Bank": "Finance",
    "Banking and finance": "Finance",
    "Bankruptcy attorney": "Legal Services",
    "Bankruptcy service": "Legal Services",
    "Banner store": "Retail",
    "Banquet hall": "Event Services",
    "Baptist church": "Religion",
    "Bar": "Food & Drink",
    "Bar & grill": "Food & Drink",
    "Barbecue area": "Recreation",
    "Barbecue restaurant": "Restaurant",
    "Barber shop": "Personal Care",
    "Bariatric surgeon": "Doctors",
    "Barrister": "Legal Services",
    "Baseball": "Sports",
    "Baseball club": "Sports",
    "Baseball field": "Sports",
    "Baseball goods store": "Retail",
    "Basilica": "Religion",
    "Basketball club": "Sports",
    "Basketball court": "Sports",
    "Basketball court contractor": "Construction",
    "Bathroom remodeler": "Construction",
    "Bathroom supply store": "Retail",
    "Battery manufacturer": "Manufacturing",
    "Battery store": "Retail",
    "Batting cage center": "Sports",
    "Bay": "Nature",
    "Beach": "Nature",
    "Beach clothing store": "Retail",
    "Beach entertainment shop": "Retail",
    "Beach pavillion": "Recreation",
    "Beach volleyball court": "Sports",
    "Bearing supplier": "Industrial",
    "Beautician": "Personal Care",
    "Beauty": "Personal Care",
    "Beauty product supplier": "Retail",
    "Beauty products wholesaler": "Wholesale",
    "Beauty salon": "Personal Care",
    "Beauty school": "Education",
    "Beauty supply store": "Retail",
    "Bed & breakfast": "Lodging",
    "Beer distributor": "Wholesale",
    "Beer garden": "Food & Drink",
    "Beer hall": "Food & Drink",
    "Beer store": "Retail",
    "Belgian restaurant": "Restaurant",
    "Beverage distributor": "Wholesale",
    "Bicycle club": "Sports",
    "Bicycle rack": "Infrastructure",
    "Bicycle rental service": "Transport",
    "Bicycle repair shop": "Automotive",
    "Bicycle Shop": "Retail",
    "Bicycle store": "Retail",
    "Bicycle wholesaler": "Wholesale",
    "Bike sharing station": "Transport",
    "Biking trail": "Recreation",
    "Bikram yoga studio": "Fitness",
    "Bingo hall": "Entertainment",
    "Biofeedback therapist": "Doctors",
    "Biotechnology company": "Industry",
    "Bird control service": "Services",
    "Bird watching area": "Recreation",
    "Birth center": "Doctors",
    "Bistro": "Restaurant",
    "Blast cleaning service": "Services",
    "Blood bank": "Doctors",
    "Blood donation center": "Doctors",
    "Blueprint service": "Services",
    "Blues club": "Entertainment",
    "BMW dealer": "Automotive",
    "BMW motorcycle dealer": "Automotive",
    "BMX track": "Sports",
    "Boarding house": "Lodging",
    "Boat accessories supplier": "Retail",
    "Boat builders": "Manufacturing",
    "Boat club": "Recreation",
    "Boat cover supplier": "Retail",
    "Boat dealer": "Retail",
    "Boat ramp": "Infrastructure",
    "Boat rental service": "Transport",
    "Boat repair shop": "Services",
    "Boat storage facility": "Logistics",
    "Boat tour agency": "Travel",
    "Body piercing shop": "Personal Care",
    "Body shaping class": "Fitness",
    "Boiler supplier": "Industrial",
    "Book publisher": "Media",
    "Book store": "Retail",
    "Bookkeeping service": "Finance",
    "Boot camp": "Fitness",
    "Boot store": "Retail",
    "Border crossing station": "Government",
    "Botanical garden": "Nature",
    "Bottled water supplier": "Wholesale",
    "Bouncy castle hire": "Entertainment",
    "Boutique": "Retail",
    "Bowling alley": "Entertainment",
    "Bowling supply shop": "Retail",
    "Boxing club": "Sports",
    "Boxing gym": "Fitness",
    "Boxing ring": "Sports",
    "Boys' high school": "Education",
    "BPO company": "Business Services",
    "Brake shop": "Automotive",
    "Branding agency": "Marketing",
    "Brazilian restaurant": "Restaurant",
    "Breakfast restaurant": "Restaurant",
    "Brewery": "Food & Drink",
    "Brewpub": "Food & Drink",
    "Bridal shop": "Retail",
    "Bridge": "Infrastructure",
    "Bridge club": "Entertainment",
    "Brunch restaurant": "Restaurant",
    "Bubble tea store": "Food & Drink",
    "Buffet restaurant": "Restaurant",
    "Bugatti dealer": "Automotive",
    "Buick dealer": "Automotive",
    "Building consultant": "Construction",
    "Building designer": "Construction",
    "Building firm": "Construction",
    "Building inspector": "Government",
    "Building materials store": "Retail",
    "Building materials supplier": "Wholesale",
    "Building restoration service": "Construction",
    "Building society": "Finance",
    "Bungee jumping center": "Entertainment",
    "Burglar alarm store": "Retail",
    "Burmese restaurant": "Restaurant",
    "Burrito restaurant": "Restaurant",
    "Bus charter": "Transport",
    "Bus company": "Transport",
    "Bus depot": "Transport",
    "Bus station": "Transport",
    "Bus stop": "Transport",
    "Bus ticket agency": "Travel",
    "Bus tour agency": "Travel",
    "Business administration service": "Business Services",
    "Business attorney": "Legal Services",
    "Business banking service": "Finance",
    "Business broker": "Finance",
    "Business center": "Business Services",
    "Business development service": "Business Services",
    "Business management consultant": "Business Services",
    "Business networking company": "Business Services",
    "Business park": "Infrastructure",
    "Business related": "Business Services",
    "Business to business service": "Business Services",
    "Butcher shop": "Retail",
    "Cabin rental agency": "Lodging",
    "Cabinet maker": "Construction",
    "Cabinet store": "Retail",
    "Cadillac dealer": "Automotive",
    "Cafe": "Food & Drink",
    "Cafeteria": "Food & Drink",
    "Cajun restaurant": "Restaurant",
    "Cake shop": "Retail",
    "Californian restaurant": "Restaurant",
    "Call center": "Business Services",
    "Camera repair shop": "Services",
    "Camera store": "Retail",
    "Campground": "Lodging",
    "Camping cabin": "Lodging",
    "Camping store": "Retail",
    "Canal": "Nature",
    "Cancer treatment center": "Doctors",
    "Candle store": "Retail",
    "Candy store": "Retail",
    "Cannabis club": "Retail",
    "Cannabis store": "Retail",
    "Cannery": "Manufacturing",
    "Canoe & kayak rental service": "Transport",
    "Canoe & kayak store": "Retail",
    "Canoe & kayak tour agency": "Travel",
    "Cantonese restaurant": "Restaurant",
    "Capoeira school": "Fitness",
    "Car accessories store": "Retail",
    "Car battery store": "Retail",
    "Car dealer": "Automotive",
    "Car detailing service": "Automotive",
    "Car factory": "Manufacturing",
    "Car finance and loan company": "Finance",
    "Car leasing service": "Automotive",
    "Car manufacturer": "Manufacturing",
    "Car racing track": "Entertainment",
    "Car rental": "Transport",
    "Car rental agency": "Transport",
    "Car repair and maintenance service": "Automotive",
    "Car security system installer": "Automotive",
    "Car sharing location": "Transport",
    "Car stereo store": "Retail",
    "Car wash": "Automotive",
    "Cardiologist": "Doctors",
    "Cardiovascular and thoracic surgeon": "Doctors",
    "Career guidance service": "Education",
    "Caribbean restaurant": "Restaurant",
    "Carpenter": "Construction",
"Carpet cleaning service": "Services",
    "Carport and pergola builder": "Construction",
    "Carriage ride service": "Entertainment",
    "Cars": "Automotive",
    "Casino": "Entertainment",
    "Castle": "Cultural",
    "Cat boarding service": "Pet Services",
    "Cat breeder": "Pet Services",
    "Caterer": "Food & Drink",
    "Catering food and drink supplier": "Wholesale",
    "Cathedral": "Religion",
    "Catholic cathedral": "Religion",
    "Catholic church": "Religion",
    "Catholic school": "Education",
    "Cattery": "Pet Services",
    "Cell phone store": "Retail",
    "Cemetery": "Cultural",
    "Central bank": "Finance",
    "Certified public accountant": "Finance",
    "Chamber of Commerce": "Government",
    "Chapel": "Religion",
    "Charcuterie": "Retail",
    "Charity": "Non-Profit",
    "Chartered accountant": "Finance",
    "Chauffeur service": "Transport",
    "Check cashing service": "Finance",
    "Cheese manufacturer": "Manufacturing",
    "Cheese shop": "Retail",
    "Cheesesteak restaurant": "Restaurant",
    "Chemical engineering service": "Industry",
    "Chemical industry": "Industry",
    "Chemical manufacturer": "Manufacturing",
    "Chemical plant": "Manufacturing",
    "Chemical wholesaler": "Wholesale",
    "Chevrolet dealer": "Automotive",
    "Chicken restaurant": "Restaurant",
    "Chicken shop": "Retail",
    "Chicken wings restaurant": "Restaurant",
    "Child care agency": "Education",
    "Child health care centre": "Doctors",
    "Childbirth class": "Education",
    "Children's amusement center": "Entertainment",
    "Children's camp": "Recreation",
    "Children's clothing store": "Retail",
    "Children's club": "Education",
    "Children's hospital": "Doctors",
    "Children's party service": "Entertainment",
    "Children's store": "Retail",
    "Chimney services": "Services",
    "Chimney sweep": "Services",
    "Chinese medicine clinic": "Doctors",
    "Chinese medicine store": "Retail",
    "Chinese noodle restaurant": "Restaurant",
    "Chinese restaurant": "Restaurant",
    "Chiropractor": "Doctors",
    "Chocolate shop": "Retail",
    "Chophouse restaurant": "Restaurant",
    "Christian church": "Religion",
    "Christmas store": "Retail",
    "Chrysler dealer": "Automotive",
    "Church": "Religion",
    "Church of Christ": "Religion",
    "Church of Jesus Christ of Latter-day Saints": "Religion",
    "Church of the Nazarene": "Religion",
    "Cider bar": "Food & Drink",
    "Cigar shop": "Retail",
    "Circus": "Entertainment",
    "City clerk's office": "Government",
    "City courthouse": "Government",
    "City department of transportation": "Government",
    "City government office": "Government",
    "City Hall": "Government",
    "City or town hall": "Government",
    "City park": "Nature",
    "City tax office": "Government",
    "Civic center": "Government",
    "Civil engineer": "Construction",
    "Civil engineering company": "Construction",
    "Civil law attorney": "Legal Services",
    "Civil police": "Government",
    "Classified ads newspaper publisher": "Media",
    "Cleaners": "Services",
    "Cleaning products supplier": "Wholesale",
    "Cleaning service": "Services",
    "Clothing alteration service": "Personal Care",
    "Clothing store": "Retail",
    "Clothing supplier": "Wholesale",
    "Club": "Entertainment",
    "Coaching center": "Education",
    "Coast guard station": "Government",
    "Cocktail bar": "Food & Drink",
    "Coffee roasters": "Food & Drink",
    "Coffee shop": "Food & Drink",
    "Coffee stand": "Food & Drink",
    "Coin dealer": "Retail",
    "Cold storage facility": "Logistics",
    "Collectibles store": "Retail",
    "College": "Education",
    "Colombian restaurant": "Restaurant",
    "Comedy club": "Entertainment",
    "Comic book store": "Retail",
    "Commercial agent": "Business Services",
    "Commercial photographer": "Media",
    "Commercial printer": "Business Services",
    "Commercial real estate agency": "Real Estate",
    "Commissioner for Oaths": "Legal Services",
    "Communications tower": "Infrastructure",
    "Community center": "Community",
    "Community college": "Education",
    "Community garden": "Community",
    "Community health centre": "Doctors",
    "Company": "Business Services",
    "Computer club": "Education",
    "Computer consultant": "IT Services",
    "Computer networking service": "IT Services",
    "Computer repair service": "IT Services",
    "Computer security service": "IT Services",
    "Computer service": "IT Services",
    "Computer software store": "Retail",
    "Computer store": "Retail",
    "Computer support and services": "IT Services",
    "Computer training school": "Education",
    "Concert hall": "Entertainment",
    "Concrete contractor": "Construction",
    "Concrete product supplier": "Wholesale",
    "Condominium complex": "Real Estate",
    "Condominium rental agency": "Real Estate",
    "Confectionery store": "Retail",
    "Confectionery wholesaler": "Wholesale",
    "Conference center": "Business Services",
    "Conservatory supply & installation": "Construction",
    "Consignment shop": "Retail",
    "Construction": "Construction",
    "Construction and maintenance office": "Construction",
    "Construction company": "Construction",
    "Construction equipment supplier": "Wholesale",
    "Construction machine dealer": "Wholesale",
    "Construction machine rental service": "Construction",
    "Construction material wholesaler": "Wholesale",
    "Consultant": "Business Services",
    "Consumer advice center": "Community",
    "Container service": "Logistics",
    "Container supplier": "Wholesale",
    "Container terminal": "Logistics",
    "Containers supplier": "Wholesale",
    "Contractor": "Construction",
    "Convenience store": "Retail",
    "Convent": "Religion",
    "Convention center": "Business Services",
    "Convention information bureau": "Travel",
    "Conveyor belt sushi restaurant": "Restaurant",
    "Cookie shop": "Retail",
    "Cooking class": "Education",
    "Copier repair service": "IT Services",
    "Copper supplier": "Wholesale",
    "Copy shop": "Services",
    "Copywriting service": "Marketing",
    "Corporate campus": "Business Services",
    "Corporate office": "Business Services",
    "Cosmetic dentist": "Doctors",
    "Cosmetic surgeon": "Doctors",
    "Cosmetics industry": "Manufacturing",
    "Cosmetics store": "Retail",
    "Cosmetics wholesaler": "Wholesale",
    "Cottage rental": "Lodging",
    "Counselor": "Doctors",
    "Countertop contractor": "Construction",
    "Countertop store": "Retail",
    "Country club": "Recreation",
    "Country food restaurant": "Restaurant",
    "County court": "Government",
    "County government office": "Government",
    "Courier service": "Logistics",
    "Court reporter": "Legal Services",
    "Courthouse": "Government",
    "Coworking space": "Business Services",
    "Crab house": "Restaurant",
    "Craft store": "Retail",
    "Crane rental agency": "Construction",
    "Crane service": "Construction",
    "Craniosacral therapy": "Doctors",
    "Credit counseling service": "Finance",
    "Credit reporting agency": "Finance",
    "Credit union": "Finance",
    "Cremation service": "Services",
    "Creole restaurant": "Restaurant",
    "Creperie": "Restaurant",
    "Criminal justice attorney": "Legal Services",
    "Crop grower": "Agriculture",
    "Cruise agency": "Travel",
    "Cruise line company": "Travel",
    "Cruise terminal": "Transport",
    "Crypto ATM": "Finance",
    "Cuban restaurant": "Restaurant",
    "Culinary school": "Education",
    "Cultural association": "Cultural",
    "Cultural center": "Cultural",
    "Cultural landmark": "Cultural",
    "Cupcake shop": "Retail",
"Custom home builder": "Construction",
    "Custom label printer": "Printing",
    "Custom t-shirt store": "Retail",
    "Customs broker": "Logistics",
    "Customs office": "Government",
    "Customs warehouse": "Logistics",
    "Dairy farm": "Agriculture",
    "Dairy farm equipment supplier": "Agriculture",
    "Dairy store": "Retail",
    "Dairy supplier": "Wholesale",
    "Dance club": "Entertainment",
    "Dance company": "Entertainment",
    "Dance hall": "Entertainment",
    "Dance pavillion": "Entertainment",
    "Dance school": "Education",
    "Dance store": "Retail",
    "Data recovery service": "IT Services",
    "Database management company": "IT Services",
    "Day care center": "Child Care",
    "Day spa": "Wellness",
    "Deaf service": "Social Services",
    "Debris removal service": "Cleaning",
    "Debt collection agency": "Finance",
    "Decal supplier": "Printing",
    "Deck builder": "Construction",
    "Deli": "Food",
    "Delivery service": "Logistics",
    "Demolition contractor": "Construction",
    "Dental clinic": "Doctors",
    "Dental hygienist": "Doctors",
    "Dental implants periodontist": "Doctors",
    "Dental implants provider": "Doctors",
    "Dental insurance agency": "Insurance",
    "Dental laboratory": "Doctors",
    "Dental school": "Education",
    "Dental supply store": "Medical Supplies",
    "Dentist": "Doctors",
    "Denture care center": "Doctors",
    "Department of motor vehicles": "Government",
    "Department of Social Services": "Government",
    "Department of Transportation": "Government",
    "Department store": "Retail",
    "Dermatologist": "Doctors",
    "Design": "Creative Services",
    "Design agency": "Creative Services",
    "Design engineer": "Engineering",
    "Design institute": "Education",
    "Dessert restaurant": "Food",
    "Dessert shop": "Food",
    "Diabetes center": "Doctors",
    "Diabetes equipment supplier": "Medical Supplies",
    "Diagnostic center": "Doctors",
    "Dialysis center": "Doctors",
    "Diesel engine repair service": "Auto Services",
    "Diesel fuel supplier": "Energy",
    "Dietitian": "Doctors",
    "Digital printer": "Printing",
    "Digital printing service": "Printing",
    "Diner": "Food",
    "Dinner theater": "Entertainment",
    "Direct mail advertising": "Advertising",
    "Dirt supplier": "Construction",
    "Disability services and support organization": "Social Services",
    "Disc golf course": "Sports",
    "Discount store": "Retail",
    "Discount supermarket": "Retail",
    "Distillery": "Food Production",
    "Distribution service": "Logistics",
    "District attorney": "Government",
    "District government office": "Government",
    "District Justice": "Government",
    "Dive club": "Recreation",
    "Dive shop": "Retail",
    "Diving center": "Recreation",
    "Divorce lawyer": "Legal",
    "Divorce service": "Legal",
    "DJ service": "Entertainment",
    "Do-it-yourself shop": "Retail",
    "Dock builder": "Construction",
    "Doctor": "Doctors",
    "Dog breeder": "Animal Services",
    "Dog day care center": "Animal Services",
    "Dog park": "Recreation",
    "Dog trainer": "Animal Services",
    "Dog walker": "Animal Services",
    "Dogsled ride service": "Tourism",
    "Dollar store": "Retail",
    "Domestic airport": "Transportation",
    "Dominican restaurant": "Food",
    "Donations center": "Social Services",
    "Donut shop": "Food",
    "Door shop": "Retail",
    "Door supplier": "Construction",
    "Doula": "Doctors",
    "Drafting equipment supplier": "Construction",
    "Drafting service": "Construction",
    "Drainage service": "Construction",
    "Dressmaker": "Fashion",
    "Drilling contractor": "Construction",
    "Drinking water fountain": "Public Services",
    "Drive-in movie theater": "Entertainment",
    "Driver's license office": "Government",
    "Driving school": "Education",
    "Drone service": "IT Services",
    "Drug store": "Retail",
    "Drug testing service": "Doctors",
    "Dry cleaner": "Cleaning",
    "Dry ice supplier": "Industrial Supplies",
    "Dry wall contractor": "Construction",
    "Ducati dealer": "Auto Sales",
    "Dude ranch": "Lodging",
    "Dumpling restaurant": "Food",
    "Dumpster rental service": "Cleaning",
    "Dune": "Nature",
    "Duty free store": "Retail",
    "E-commerce service": "IT Services",
    "E commerce agency": "IT Services",
    "Ear piercing service": "Beauty",
    "Earth works company": "Construction",
    "Eastern European restaurant": "Food",
    "Eating disorder treatment center": "Doctors",
    "Eclectic restaurant": "Food",
    "Economic development agency": "Government",
    "Education": "Education",
    "Education center": "Education",
    "Educational consultant": "Education",
    "Educational institution": "Education",
    "Educational testing service": "Education",
    "Elder law attorney": "Legal",
    "Electric bicycle store": "Retail",
    "Electric generator shop": "Retail",
    "Electric motor repair shop": "Auto Services",
    "Electric motor scooter dealer": "Auto Sales",
    "Electric motor store": "Retail",
    "Electric motor vehicle dealer": "Auto Sales",
    "Electric motorcycle dealer": "Auto Sales",
    "Electric utility company": "Energy",
    "Electric vehicle charging station": "Energy",
    "Electric vehicle charging station contractor": "Construction",
    "Electrical engineer": "Engineering",
    "Electrical equipment supplier": "Industrial Supplies",
    "Electrical installation service": "Construction",
    "Electrical substation": "Energy",
    "Electrical supply store": "Retail",
    "Electrician": "Construction",
    "Electrolysis hair removal service": "Beauty",
    "Electronic engineering service": "Engineering",
    "Electronic parts supplier": "Wholesale",
    "Electronics company": "Electronics",
    "Electronics engineer": "Engineering",
    "Electronics manufacturer": "Electronics",
    "Electronics repair shop": "Electronics",
    "Electronics store": "Retail",
    "Electronics vending machine": "Retail",
    "Elementary school": "Education",
    "Elevated": "Transportation",
    "Elevator service": "Construction",
    "Embroidery service": "Printing",
    "Embroidery shop": "Retail",
    "Emergency care physician": "Doctors",
    "Emergency care service": "Doctors",
    "Emergency dental service": "Doctors",
    "Emergency locksmith service": "Emergency Services",
    "Emergency room": "Doctors",
    "Emergency training": "Education",
    "Emergency veterinarian service": "Animal Services",
    "Employment agency": "Recruitment",
    "Employment attorney": "Legal",
    "Employment center": "Recruitment",
    "Endocrinologist": "Doctors",
    "Endodontist": "Doctors",
    "Endoscopist": "Doctors",
    "Energy equipment and solutions": "Energy",
    "Energy supplier": "Energy",
    "Engine rebuilding service": "Auto Services",
    "Engineer": "Engineering",
    "Engineering consultant": "Engineering",
    "Engineering school": "Education",
    "English restaurant": "Food",
    "Entertainer": "Entertainment",
    "Entertainment agency": "Entertainment",
    "Entertainment and recreation": "Entertainment",
    "Environmental attorney": "Legal",
    "Environmental consultant": "Consulting",
    "Environmental engineer": "Engineering",
    "Environmental health service": "Doctors",
    "Environmental organization": "Nonprofit",
    "Environmental program": "Government",
    "Environmental protection organization": "Nonprofit",
    "Episcopal church": "Religion",
    "Equestrian facility": "Sports",
    "Equipment rental agency": "Rental",
    "Equipment supplier": "Wholesale",
    "Escrow service": "Finance",
    "Espresso bar": "Food & Drink",
    "Establishment": "General",
    "Estate appraiser": "Real Estate",
    "Estate liquidator": "Real Estate",
    "Estate litigation attorney": "Legal",
    "Estate planning attorney": "Legal",
    "Ethiopian restaurant": "Food & Drink",
    "Ethnographic museum": "Culture",
    "European restaurant": "Food & Drink",
    "Event management company": "Event Services",
    "Event planner": "Event Services",
    "Event technology service": "Event Services",
    "Event venue": "Event Services",
    "Excavating contractor": "Construction",
    "Executive suite rental agency": "Real Estate",
    "Exercise equipment store": "Retail",
    "Exhibition planner": "Event Services",
    "Exporter": "Trade",
    "Eye care center": "Doctors",
    "Eyelash salon": "Beauty",
    "Fabric product manufacturer": "Manufacturing",
    "Fabric store": "Retail",
    "Fabrication engineer": "Engineering",
    "Facial spa": "Beauty",
    "Factory equipment supplier": "Industrial",
    "Faculty of pharmacy": "Education",
    "Fairground": "Entertainment",
    "Family counselor": "Doctors",
    "Family day care service": "Childcare",
    "Family law attorney": "Legal",
    "Family planning center": "Doctors",
    "Family practice physician": "Doctors",
    "Family restaurant": "Food & Drink",
    "Family service center": "Social Services",
    "Farm": "Agriculture",
    "Farm equipment repair service": "Agriculture",
    "Farm equipment supplier": "Agriculture",
    "Farm shop": "Retail",
    "Farmers' market": "Retail",
    "Fashion accessories store": "Retail",
    "Fashion designer": "Fashion",
    "Fast food restaurant": "Food & Drink",
    "Fastener supplier": "Industrial",
    "Federal courthouse": "Government",
    "Federal credit union": "Finance",
    "Federal government office": "Government",
    "Federal police": "Government",
    "Feed manufacturer": "Agriculture",
    "Fence contractor": "Construction",
    "Fence supply store": "Retail",
    "Fencing school": "Education",
    "Feng shui consultant": "Consulting",
    "Ferry service": "Transportation",
    "Ferry terminal": "Transportation",
    "Fertilizer supplier": "Agriculture",
    "Festival": "Entertainment",
    "Fiber optic products supplier": "Technology",
    "Fiberglass supplier": "Industrial",
    "Filipino restaurant": "Food & Drink",
    "Film production company": "Media",
    "Finance broker": "Finance",
    "Financial advisor": "Finance",
    "Financial audit": "Finance",
    "Financial consultant": "Finance",
    "Financial institution": "Finance",
    "Financial planner": "Finance",
    "Fine dining restaurant": "Food & Drink",
    "Fingerprinting service": "Security",
    "Finishing materials supplier": "Construction",
    "Fire alarm supplier": "Security",
    "Fire damage restoration service": "Home Services",
    "Fire protection consultant": "Security",
    "Fire protection equipment supplier": "Security",
    "Fire protection service": "Security",
    "Fire station": "Government",
    "Firearms academy": "Education",
    "Fireplace store": "Retail",
    "Fireworks supplier": "Retail",
    "Fish & chips restaurant": "Food & Drink",
    "Fish processing": "Food Industry",
    "Fishing area": "Recreation",
    "Fishing camp": "Recreation",
    "Fishing charter": "Recreation",
    "Fishing lake": "Recreation",
    "Fishing pier": "Recreation",
    "Fishing pond": "Recreation",
    "Fishing store": "Retail",
    "Fitness center": "Fitness",
    "Fitness equipment wholesaler": "Retail",
    "Fixed-base operator": "Transportation",
    "Flea market": "Retail",
    "Flight school": "Education",
    "Flooring contractor": "Construction",
    "Flooring store": "Retail",
    "Florist": "Retail",
    "Flower designer": "Retail",
    "Flower market": "Retail",
    "Food and beverage consultant": "Consulting",
    "Food and drink": "Food & Drink",
    "Food bank": "Social Services",
    "Food broker": "Food Industry",
    "Food court": "Food & Drink",
    "Food machinery supplier": "Industrial",
    "Food manufacturer": "Food Industry",
    "Food manufacturing supply": "Food Industry",
    "Food processing company": "Food Industry",
    "Food processing equipment": "Food Industry",
    "Food producer": "Food Industry",
    "Food products supplier": "Food Industry",
    "Food service": "Food Industry",
    "Food store": "Retail",
    "Foot care": "Doctors",
    "Ford dealer": "Automotive",
    "Foreclosure service": "Legal",
    "Foreign consulate": "Government",
    "Forensic consultant": "Consulting",
    "Forestry office": "Government",
    "Forestry service": "Government",
    "Forklift dealer": "Industrial",
    "Forklift rental service": "Industrial",
    "Formal wear store": "Retail",
    "Foundation": "Organization",
    "Foundry": "Manufacturing",
    "Fountain contractor": "Construction",
    "Fraternal organization": "Organization",
    "Free clinic": "Doctors",
    "Free parking lot": "Transportation",
    "Freestyle wrestling": "Sports",
    "Freight forwarding service": "Logistics",
    "French restaurant": "Food & Drink",
    "Fresh food market": "Retail",
    "Fried chicken takeaway": "Food & Drink",
    "Frozen yogurt shop": "Food & Drink",
    "Fuel supplier": "Energy",
    "Function room facility": "Event Services",
    "Funeral home": "Services",
    "Furnace repair service": "Home Services",
    "Furnished apartment building": "Real Estate",
    "Furniture accessories": "Retail",
    "Furniture maker": "Manufacturing",
    "Furniture manufacturer": "Manufacturing",
    "Furniture rental service": "Retail",
    "Furniture store": "Retail",
    "Furniture wholesaler": "Retail",
    "Fusion restaurant": "Food & Drink",
    "Game store": "Retail",
    "Garage door supplier": "Retail",
    "Garbage collection service": "Public Services",
    "Garbage dump": "Public Services",
    "Garden": "Recreation",
    "Garden center": "Retail",
    "Gardener": "Home Services",
    "Gas company": "Energy",
    "Gas engineer": "Energy",
    "Gas installation service": "Energy",
    "Gas station": "Energy",
    "Gastroenterologist": "Doctors",
    "Gastrointestinal surgeon": "Doctors",
    "Gastropub": "Food & Drink",
    "Gated community": "Real Estate",
    "Gay bar": "Entertainment",
    "Gay night club": "Entertainment",
    "Gazebo builder": "Construction",
    "General contractor": "Construction",
    "General hospital": "Doctors",
    "General practice attorney": "Legal",
    "General practitioner": "Doctors",
    "General store": "Retail",
    "Geotechnical engineer": "Engineering",
    "Geriatrician": "Doctors",
    "German restaurant": "Food & Drink",
    "Ghost town": "Tourism",
    "Gift shop": "Retail",
    "Girl bar": "Entertainment",
    "Glass industry": "Manufacturing",
    "Glass manufacturer": "Manufacturing",
    "Glass repair service": "Home Services",
    "Glass shop": "Retail",
    "Glazier": "Construction",
    "Gluten-free restaurant": "Food & Drink",
    "GMC dealer": "Automotive",
    "Go-kart track": "Entertainment",
    "Gold dealer": "Retail",
    "Golf cart dealer": "Sports",
    "Golf club": "Sports",
    "Golf course": "Sports",
    "Golf driving range": "Sports",
    "Golf instructor": "Sports",
    "Golf shop": "Retail",
    "Gondola lift station": "Transportation",
    "Gourmet grocery store": "Retail",
    "Government": "Government",
    "Government hospital": "Doctors",
    "Government office": "Government",
    "Government school": "Education",
    "GPS supplier": "Technology",
    "Graduate school": "Education",
    "Grain elevator": "Agriculture",
"Granite supplier": "Industrial",
    "Graphic designer": "Creative Services",
    "Gravel pit": "Industrial",
    "Greek restaurant": "Food & Drink",
    "Green energy supplier": "Energy",
    "Greenhouse": "Agriculture",
    "Grill": "Food & Drink",
    "Grill store": "Retail",
    "Grocery delivery service": "Retail",
    "Grocery store": "Retail",
    "Guest house": "Lodging",
    "Gun shop": "Retail",
    "Gurudwara": "Religion",
    "Gutter cleaning service": "Home Services",
    "Gutter service": "Home Services",
    "Gym": "Fitness",
    "Gymnasium school": "Education",
    "Gymnastics center": "Sports",
    "Gymnastics club": "Sports",
    "Gynecologist": "Doctors",
    "Hair extensions supplier": "Beauty",
    "Hair removal service": "Beauty",
    "Hair replacement service": "Beauty",
    "Hair salon": "Beauty",
    "Hair transplantation clinic": "Doctors",
    "Hairdresser": "Beauty",
    "Haitian restaurant": "Food & Drink",
    "Halal restaurant": "Food & Drink",
    "Hamburger restaurant": "Food & Drink",
    "Hand surgeon": "Doctors",
    "Handicapped transportation service": "Transportation",
    "Handyman/Handywoman/Handyperson": "Home Services",
    "Hang gliding center": "Recreation",
    "Harbor": "Transportation",
    "Hardware store": "Retail",
    "Harley-Davidson dealer": "Automotive",
    "Hat shop": "Retail",
    "Haunted house": "Entertainment",
    "Hawaiian restaurant": "Food & Drink",
    "Hay supplier": "Agriculture",
    "Head start center": "Education",
    "Health": "Doctors",
    "Health and beauty": "Beauty",
    "Health and beauty shop": "Retail",
    "Health care facility": "Doctors",
    "Health consultant": "Doctors",
    "Health counselor": "Doctors",
    "Health food restaurant": "Food & Drink",
    "Health food store": "Retail",
    "Health insurance agency": "Finance",
    "Health resort": "Wellness",
    "Health spa": "Wellness",
    "Hearing aid store": "Doctors",
    "Heart hospital": "Doctors",
    "Heating contractor": "Home Services",
    "Heating oil supplier": "Energy",
    "Helicopter charter": "Transportation",
    "Helicopter tour agency": "Tourism",
    "Heliport": "Transportation",
    "Hematologist": "Doctors",
    "Hepatologist": "Doctors",
    "Herb shop": "Retail",
    "Herbal medicine store": "Doctors",
    "Herbalist": "Doctors",
    "Heritage building": "Culture",
    "Heritage museum": "Culture",
    "Heritage railroad": "Tourism",
    "High school": "Education",
    "Hiking area": "Recreation",
    "Hiking guide": "Recreation",
    "Hindu temple": "Religion",
    "Hip hop dance class": "Education",
    "Historic city center": "Tourism",
    "Historical landmark": "Tourism",
    "Historical place": "Tourism",
    "Historical place museum": "Culture",
    "Historical society": "Organization",
    "History museum": "Culture",
    "Hobby store": "Retail",
    "Hockey club": "Sports",
    "Holding company": "Business Services",
    "Holiday apartment": "Lodging",
    "Holiday apartment rental": "Lodging",
    "Holiday park": "Lodging",
    "Holistic medicine practitioner": "Doctors",
    "Home audio store": "Retail",
    "Home automation company": "Technology",
    "Home builder": "Construction",
    "Home cinema installation": "Home Services",
    "Home goods store": "Retail",
    "Home health care service": "Doctors",
    "Home help": "Doctors",
    "Home help service agency": "Doctors",
    "Home improvement store": "Retail",
    "Home inspector": "Real Estate",
    "Home insurance agency": "Finance",
    "Home staging service": "Real Estate",
    "Home theater store": "Retail",
    "Homeless shelter": "Social Services",
    "Homeopath": "Doctors",
    "Homeopathic pharmacy": "Doctors",
    "Homeowners' association": "Organization",
    "Honda dealer": "Automotive",
    "Honduran restaurant": "Food & Drink",
    "Honey farm": "Agriculture",
    "Hookah bar": "Food & Drink",
    "Horse boarding stable": "Agriculture",
    "Horse riding field": "Recreation",
    "Horse riding school": "Education",
    "Horse trainer": "Sports",
    "Horseback riding service": "Recreation",
    "Hose supplier": "Industrial",
    "Hospice": "Doctors",
    "Hospital": "Doctors",
    "Hospital department": "Doctors",
    "Hospital equipment and supplies": "Doctors",
    "Hostel": "Lodging",
    "Hot dog restaurant": "Food & Drink",
    "Hot dog stand": "Food & Drink",
    "Hot pot restaurant": "Food & Drink",
    "Hot spring": "Tourism",
    "Hot tub repair service": "Home Services",
    "Hot tub store": "Retail",
    "Hotel": "Lodging",
    "House cleaning service": "Home Services",
    "House sitter": "Home Services",
    "Housing authority": "Government",
    "Housing complex": "Real Estate",
    "Housing development": "Real Estate",
    "Housing society": "Organization",
    "Hub cap supplier": "Automotive",
    "Human resource consulting": "Business Services",
    "Hunting and fishing store": "Retail",
    "Hunting club": "Recreation",
    "Hunting store": "Retail",
    "HVAC contractor": "Construction",
    "Hydraulic equipment supplier": "Industrial",
    "Hydraulic repair service": "Industrial",
    "Hydroelectric power plant": "Energy",
    "Hygiene articles wholesaler": "Wholesale",
    "Hypermarket": "Retail",
    "Hypnotherapy service": "Doctors",
    "Hyundai dealer": "Automotive",
    "Ice cream shop": "Food & Drink",
    "Ice skating rink": "Recreation",
    "Ice supplier": "Retail",
    "Image consultant": "Consulting",
    "Immigration & naturalization service": "Government",
    "Immigration attorney": "Legal",
    "Immunologist": "Doctors",
    "Import export company": "Trade",
    "Importer": "Trade",
    "Inclined railway station": "Transportation",
    "Income protection insurance agency": "Finance",
    "Indian grocery store": "Retail",
    "Indian restaurant": "Food & Drink",
    "Indoor cycling": "Fitness",
    "Indoor golf course": "Sports",
    "Indoor lodging": "Lodging",
    "Indoor playground": "Recreation",
    "Indoor swimming pool": "Fitness",
    "Industrial chemicals wholesaler": "Industrial",
    "Industrial consultant": "Consulting",
    "Industrial design company": "Engineering",
    "Industrial engineer": "Engineering",
    "Industrial engineers association": "Organization",
    "Industrial equipment supplier": "Industrial",
    "Industrial gas supplier": "Industrial",
    "Industrial real estate agency": "Real Estate",
    "Industrial technical engineers association": "Organization",
    "Industrial vacuum equipment supplier": "Industrial",
    "Infectious disease physician": "Doctors",
    "Infiniti dealer": "Automotive",
    "Information centers": "Services",
    "Information services": "Services",
    "Inn": "Lodging",
    "Institute of technology": "Education",
    "Instrumentation engineer": "Engineering",
    "Insulation contractor": "Construction",
    "Insurance": "Finance",
    "Insurance agency": "Finance",
    "Insurance attorney": "Legal",
    "Insurance broker": "Finance",
    "Insurance company": "Finance",
    "Interior architect office": "Architecture",
    "Interior Decorator": "Creative Services",
    "Interior designer": "Creative Services",
    "Interior plant service": "Home Services",
    "Internal medicine ward": "Doctors",
    "International airport": "Transportation",
    "International school": "Education",
    "International trade consultant": "Consulting",
    "Internet cafe": "Technology",
    "Internet marketing service": "Marketing",
    "Internet service provider": "Technology",
    "Internet shop": "Retail",
    "Internist": "Doctors",
    "Investment bank": "Finance",
    "Investment company": "Finance",
    "Investment service": "Finance",
    "Invitation printing service": "Printing",
    "Irish pub": "Bar",
    "Irish restaurant": "Restaurant",
    "Iron works": "Manufacturing",
    "Island": "Geographical Location",
    "Israeli restaurant": "Restaurant",
    "Italian restaurant": "Restaurant",
    "IV therapy service": "Doctors",
    "Izakaya restaurant": "Restaurant",
    "Jamaican restaurant": "Restaurant",
    "Janitorial equipment supplier": "Retail",
    "Janitorial service": "Service",
    "Japanese grocery store": "Retail",
    "Japanese restaurant": "Restaurant",
    "Japanese steakhouse": "Restaurant",
    "Jazz club": "Entertainment",
    "Jeep dealer": "Automotive",
    "Jeweler": "Retail",
    "Jewelry buyer": "Retail",
    "Jewelry designer": "Retail",
    "Jewelry manufacturer": "Manufacturing",
    "Jewelry store": "Retail",
    "Judo club": "Sports",
    "Judo school": "Sports",
    "Juice shop": "Retail",
    "Jujitsu school": "Sports",
    "Junk removal service": "Service",
    "Justice department": "Government",
    "Juvenile detention center": "Government",
    "Karaoke": "Entertainment",
    "Karaoke bar": "Entertainment",
    "Karate club": "Sports",
    "Karate school": "Sports",
    "Kawasaki motorcycle dealer": "Automotive",
    "Kennel": "Pet Services",
    "Key duplication service": "Service",
    "Kia dealer": "Automotive",
    "Kickboxing school": "Sports",
    "Kindergarten": "Education",
    "Kinesiologist": "Doctors",
    "Kinesiotherapist": "Doctors",
    "Kiosk": "Retail",
    "Kitchen remodeler": "Home Services",
    "Kitchen supply store": "Retail",
    "Knife store": "Retail",
    "Korean barbecue restaurant": "Restaurant",
    "Korean church": "Religion",
    "Korean grocery store": "Retail",
    "Korean restaurant": "Restaurant",
    "Kung fu school": "Sports",
    "Labor relations attorney": "Legal Services",
    "Labor union": "Organization",
    "Laboratory": "Doctors",
    "Lactation service": "Doctors",
    "Lake": "Geographical Location",
    "Lamborghini dealer": "Automotive",
    "Lamination service": "Service",
    "Land Rover dealer": "Automotive",
    "Land surveying office": "Real Estate Services",
    "Land surveyor": "Real Estate Services",
    "Landmark": "Geographical Location",
    "Landscape architect": "Design",
    "Landscape designer": "Design",
    "Landscape lighting designer": "Design",
    "Landscaper": "Service",
    "Landscaping supply store": "Retail",
    "Laser cutting service": "Manufacturing",
    "Laser hair removal service": "Beauty Services",
    "Laser tag center": "Entertainment",
    "Latin American restaurant": "Restaurant",
    "Laundromat": "Service",
    "Laundry": "Service",
    "Law firm": "Legal Services",
    "Law library": "Education",
    "Law school": "Education",
    "Lawn care service": "Service",
    "Lawn equipment rental service": "Service",
    "Lawn irrigation equipment supplier": "Retail",
    "Lawn mower repair service": "Service",
    "Lawn mower store": "Retail",
    "Lawn sprinkler system contractor": "Service",
    "Lawyer": "Legal Services",
    "Lawyers association": "Organization",
    "Learning center": "Education",
    "Leasing service": "Service",
    "Leather goods manufacturer": "Manufacturing",
    "Leather goods store": "Retail",
    "Lebanese restaurant": "Restaurant",
    "Legal services": "Legal Services",
    "Lesbian bar": "Nightlife",
    "Lexus dealer": "Automotive",
    "Library": "Public Services",
    "License bureau": "Government",
    "Life coach": "Consulting",
    "Life insurance agency": "Insurance",
    "Light rail station": "Transportation",
    "Lighting consultant": "Consulting",
    "Lighting contractor": "Construction",
    "Lighting manufacturer": "Manufacturing",
    "Lighting store": "Retail",
    "Limousine service": "Transport",
    "Lincoln dealer": "Automotive",
    "Line marking service": "Service",
    "Lingerie store": "Retail",
    "Liquidator": "Retail",
    "Liquor store": "Retail",
    "Live music bar": "Entertainment",
    "Live music venue": "Entertainment",
    "Livestock auction house": "Agriculture",
    "Livestock breeder": "Agriculture",
    "Loan agency": "Financial Services",
    "Local government office": "Government",
    "Local history museum": "Museum",
    "Local medical services": "Doctors",
    "Locksmith": "Service",
    "Lodge": "Accommodation",
    "Lodging": "Accommodation",
    "Log home builder": "Construction",
    "Logging contractor": "Agriculture",
    "Logistics": "Logistics",
    "Logistics service": "Service",
    "Loss adjuster": "Insurance",
    "Lost property office": "Government",
    "Lounge": "Entertainment",
    "Low income housing program": "Government",
    "Luggage storage facility": "Service",
    "Luggage store": "Retail",
    "Lumber store": "Retail",
    "Lunch restaurant": "Restaurant",
    "Lymph drainage therapist": "Doctors",
    "Machine shop": "Manufacturing",
    "Machinery parts manufacturer": "Manufacturing",
    "Machining manufacturer": "Manufacturing",
    "Magistrates' court": "Government",
    "Mailbox rental service": "Service",
    "Mailbox supplier": "Retail",
    "Mailing service": "Service",
    "Make-up artist": "Beauty Services",
    "Makerspace": "Community",
    "Malaysian restaurant": "Restaurant",
    "Manufactured home transporter": "Transport",
    "Manufacturer": "Manufacturing",
    "Mapping service": "Service",
    "Marble supplier": "Retail",
    "Marina": "Recreation",
    "Marine engineer": "Engineering",
    "Marine self defense force": "Military",
    "Marine supply store": "Retail",
    "Marine surveyor": "Marine Services",
    "Market": "Retail",
    "Market researcher": "Business Services",
    "Marketing": "Business Services",
    "Marketing agency": "Business Services",
    "Marketing consultant": "Consulting",
    "Marquee hire service": "Event Services",
    "Marriage license bureau": "Government",
    "Marriage or relationship counselor": "Doctors",
    "Martial arts club": "Sports",
    "Martial arts school": "Sports",
    "Martial arts supply store": "Retail",
    "Masonry contractor": "Construction",
    "Masonry supply store": "Retail",
    "Massage school": "Education",
    "Massage service": "Beauty Services",
    "Massage spa": "Beauty Services",
    "Massage therapist": "Beauty Services",
    "Material handling equipment supplier": "Industrial Equipment",
    "Mattress store": "Retail",
    "Mazda dealer": "Automotive",
    "McLaren dealer": "Automotive",
    "Meal delivery": "Food Services",
    "Measuring instruments supplier": "Retail",
    "Meat packer": "Food Industry",
    "Meat processor": "Food Industry",
    "Meat products store": "Retail",
    "Meat wholesaler": "Food Industry",
    "Mechanic": "Service",
    "Mechanical contractor": "Construction",
    "Mechanical engineer": "Engineering",
    "Media company": "Media",
    "Media consultant": "Consulting",
    "Media house": "Media",
    "Mediation service": "Professional Services",
    "Medical billing service": "Doctors",
    "Medical Center": "Doctors",
    "Medical clinic": "Doctors",
    "Medical diagnostic imaging center": "Doctors",
    "Medical equipment supplier": "Doctors",
    "Medical examiner": "Doctors",
    "Medical group": "Doctors",
    "Medical laboratory": "Doctors",
    "Medical lawyer": "Legal Services",
    "Medical office": "Doctors",
    "Medical school": "Education",
    "Medical spa": "Beauty Services",
    "Medical supply store": "Retail",
    "Medical technology manufacturer": "Manufacturing",
    "Meditation center": "Doctors",
    "Meditation instructor": "Doctors",
    "Mediterranean restaurant": "Restaurant",
"Memorial": "Place of Remembrance",
    "Memorial park": "Park",
    "Men's clothing store": "Retail",
    "Men's health physician": "Doctors",
    "Mental health clinic": "Doctors",
    "Mental health service": "Doctors",
    "Mercedes-Benz dealer": "Automotive",
    "Metal construction company": "Construction",
    "Metal fabricator": "Manufacturing",
    "Metal finisher": "Manufacturing",
    "Metal machinery supplier": "Industrial Equipment",
    "Metal processing company": "Manufacturing",
    "Metal stamping service": "Manufacturing",
    "Metal supplier": "Retail",
    "Metal working shop": "Manufacturing",
    "Metal workshop": "Manufacturing",
    "Metaphysical supply store": "Retail",
    "Methodist church": "Religion",
    "Mexican goods store": "Retail",
    "Mexican grocery store": "Retail",
    "Mexican restaurant": "Restaurant",
    "Mid-Atlantic restaurant (US)": "Restaurant",
    "Middle Eastern restaurant": "Restaurant",
    "Middle school": "Education",
    "Midwife": "Doctors",
    "Military airport": "Military",
    "Military archive": "Government",
    "Military barracks": "Military",
    "Military base": "Military",
    "Military cemetery": "Cemetery",
    "Military hospital": "Doctors",
    "Military recruiting office": "Government",
    "Military residence": "Government",
    "Military school": "Education",
    "Mill": "Manufacturing",
    "Millwork shop": "Manufacturing",
    "Mine": "Mining",
    "MINI dealer": "Automotive",
    "Miniature golf course": "Recreation",
    "Minibus taxi service": "Transport",
    "Mining company": "Mining",
    "Mining consultant": "Consulting",
    "Mining equipment": "Retail",
    "Mirror shop": "Retail",
    "Mission": "Religion",
    "Mitsubishi dealer": "Automotive",
    "Mobile caterer": "Food Services",
    "Mobile home dealer": "Retail",
    "Mobile home park": "Accommodation",
    "Mobile home rental agency": "Real Estate",
    "Mobile home supply store": "Retail",
    "Mobile phone repair shop": "Service",
    "Mobility equipment supplier": "Retail",
    "Model shop": "Retail",
    "Modeling agency": "Entertainment",
    "Modern art museum": "Museum",
    "Monastery": "Religion",
    "Money order service": "Financial Services",
    "Money transfer service": "Financial Services",
    "Mongolian barbecue restaurant": "Restaurant",
    "Montessori school": "Education",
    "Monument": "Place of Remembrance",
    "Monument maker": "Retail",
    "Moravian church": "Religion",
    "Mortgage broker": "Financial Services",
    "Mortgage lender": "Financial Services",
    "Mortuary": "Doctors",
    "Mosque": "Religion",
    "Motel": "Accommodation",
    "Motor scooter dealer": "Automotive",
    "Motor scooter repair shop": "Service",
    "Motor vehicle dealer": "Automotive",
    "Motorcycle dealer": "Automotive",
    "Motorcycle driving school": "Education",
    "Motorcycle insurance agency": "Insurance",
    "Motorcycle parts store": "Retail",
    "Motorcycle rental agency": "Service",
    "Motorcycle repair shop": "Service",
    "Motorcycle shop": "Retail",
    "Motorsports store": "Retail",
    "Mountain cabin": "Accommodation",
    "Mountain cable car": "Transport",
    "Mountain pass": "Geographical Location",
    "Mountain peak": "Geographical Location",
    "Mountaineering class": "Education",
    "Mover": "Service",
    "Movie rental kiosk": "Retail",
    "Movie rental store": "Retail",
    "Movie studio": "Entertainment",
    "Movie theater": "Entertainment",
    "Moving and storage service": "Service",
    "Moving company": "Service",
    "Moving supply store": "Retail",
    "MRI center": "Doctors",
    "Muay Thai boxing gym": "Sports",
    "Muffler shop": "Automotive",
    "Municipal administration office": "Government",
    "Museum": "Museum",
    "Music instructor": "Education",
    "Music management and promotion": "Entertainment",
    "Music producer": "Entertainment",
    "Music school": "Education",
    "Music store": "Retail",
    "Musical club": "Entertainment",
    "Musical instrument repair shop": "Service",
    "Musical instrument store": "Retail",
    "Nail salon": "Beauty Services",
    "Nanotechnology engineering service": "Engineering",
    "National forest": "Nature",
    "National museum": "Museum",
    "National park": "Nature",
    "National reserve": "Nature",
    "Native American restaurant": "Restaurant",
    "Natural feature": "Nature",
    "Natural goods store": "Retail",
    "Natural history museum": "Museum",
    "Nature preserve": "Nature",
    "Naturopathic practitioner": "Doctors",
    "Naval base": "Military",
    "Neon sign shop": "Retail",
    "Neonatal physician": "Doctors",
    "Nepalese restaurant": "Restaurant",
    "Nephrologist": "Doctors",
    "Neurologist": "Doctors",
    "Neurophysiologist": "Doctors",
    "Neurosurgeon": "Doctors",
    "New American restaurant": "Restaurant",
    "News service": "Media",
    "Newspaper publisher": "Media",
    "Newsstand": "Retail",
    "Night club": "Entertainment",
    "Nightlife": "Entertainment",
    "Nissan dealer": "Automotive",
    "Non-denominational church": "Religion",
    "Non-governmental organization": "Organization",
    "Non-profit organization": "Organization",
    "Northern Italian restaurant": "Restaurant",
    "Notary public": "Legal Services",
    "Novelty store": "Retail",
    "Nuclear power plant": "Energy",
    "Nudist park": "Recreation",
    "Nurse practitioner": "Doctors",
    "Nursing agency": "Doctors",
    "Nursing home": "Doctors",
    "Nursing school": "Education",
    "Nutritionist": "Doctors",
    "Observation deck": "Tourism",
    "Observatory": "Tourism",
    "Obstetrician-gynecologist": "Doctors",
    "Occupational health service": "Doctors",
    "Occupational medical physician": "Doctors",
    "Occupational safety and health": "Doctors",
    "Occupational therapist": "Doctors",
    "Off-road race track": "Recreation",
    "Off roading area": "Recreation",
    "Office": "Business Services",
    "Office equipment rental service": "Service",
    "Office equipment supplier": "Retail",
    "Office furniture store": "Retail",
    "Office space rental agency": "Real Estate",
    "Office supply store": "Retail",
    "Oil & natural gas company": "Energy",
    "Oil and gas exploration service": "Energy",
    "Oil change service": "Automotive",
    "Oil field equipment supplier": "Retail",
    "Oil refinery": "Energy",
    "Oilfield": "Energy",
    "Oncologist": "Doctors",
    "Opera house": "Entertainment",
    "Ophthalmologist": "Doctors",
    "Ophthalmology clinic": "Doctors",
    "Optical instrument repair service": "Service",
    "Optician": "Doctors",
    "Optometrist": "Doctors",
    "Oral and maxillofacial surgeon": "Doctors",
    "Oral surgeon": "Doctors",
    "Organic farm": "Agriculture",
    "Organic food store": "Retail",
    "Organic restaurant": "Restaurant",
    "Organic shop": "Retail",
    "Oriental medicine store": "Retail",
    "Orthodontist": "Doctors",
    "Orthodox church": "Religion",
    "Orthopedic clinic": "Doctors",
    "Orthopedic shoe store": "Retail",
    "Orthopedic surgeon": "Doctors",
    "Orthotics & prosthetics service": "Doctors",
    "Osteopath": "Doctors",
    "Otolaryngologist": "Doctors",
    "Otolaryngology clinic": "Doctors",
    "Outdoor activity organiser": "Service",
    "Outdoor clothing and equipment shop": "Retail",
    "Outdoor furniture store": "Retail",
    "Outdoor sports store": "Retail",
    "Outdoor swimming pool": "Recreation",
    "Outerwear store": "Retail",
"Outlet mall": "Retail",
    "Outlet store": "Retail",
    "Oxygen cocktail spot": "Health and Wellness",
    "Oxygen equipment supplier": "Retail",
    "Oyster bar restaurant": "Restaurant",
    "Oyster supplier": "Retail",
    "Pacific Northwest restaurant (US)": "Restaurant",
    "Pacific Rim restaurant": "Restaurant",
    "Packaging company": "Manufacturing",
    "Packaging supply store": "Retail",
    "Pain control clinic": "Doctors",
    "Pain management physician": "Doctors",
    "Paint manufacturer": "Manufacturing",
    "Paint store": "Retail",
    "Paintball center": "Recreation",
    "Paintball store": "Retail",
    "Painter": "Service",
    "Painting": "Service",
    "Painting lessons": "Education",
    "Pakistani restaurant": "Restaurant",
    "Pallet supplier": "Retail",
    "Pancake restaurant": "Restaurant",
    "Pantry": "Retail",
    "Paper mill": "Manufacturing",
    "Paralegal services provider": "Legal Services",
    "Parapharmacy": "Retail",
    "Park": "Outdoor",
    "Park & ride": "Transport",
    "Parking": "Service",
    "Parking garage": "Service",
    "Parking lot": "Service",
    "Parking lot for bicycles": "Service",
    "Parkour spot": "Recreation",
    "Party equipment rental service": "Service",
    "Party planner": "Service",
    "Party store": "Retail",
    "Passport agent": "Service",
    "Passport photo processor": "Service",
    "Pastry shop": "Retail",
    "Patent attorney": "Legal Services",
    "Pathologist": "Doctors",
    "Patients support association": "Non-profit",
    "Patio enclosure supplier": "Retail",
    "Paving contractor": "Construction",
    "Paving materials supplier": "Retail",
    "Pawn shop": "Retail",
    "Payroll service": "Business Services",
    "Pediatric clinic": "Doctors",
    "Pediatric dentist": "Doctors",
    "Pediatric dermatologist": "Doctors",
    "Pediatric gastroenterologist": "Doctors",
    "Pediatric urologist": "Doctors",
    "Pediatrician": "Doctors",
    "Pen store": "Retail",
    "Peninsula": "Geographical Location",
    "Pentecostal church": "Religion",
    "Performing arts": "Entertainment",
    "Performing arts group": "Entertainment",
    "Performing arts theater": "Entertainment",
    "Perfume store": "Retail",
    "Perinatal center": "Doctors",
    "Periodontist": "Doctors",
    "Permanent make-up clinic": "Beauty Services",
    "Personal chef service": "Service",
    "Personal concierge service": "Service",
    "Personal injury attorney": "Legal Services",
    "Personal trainer": "Health and Wellness",
    "Personal watercraft dealer": "Retail",
    "Peruvian restaurant": "Restaurant",
    "Pest control service": "Service",
    "Pet adoption service": "Service",
    "Pet boarding service": "Service",
    "Pet care": "Service",
    "Pet care service": "Service",
    "Pet cemetery": "Cemetery",
    "Pet funeral service": "Service",
    "Pet groomer": "Service",
    "Pet moving service": "Service",
    "Pet sitter": "Service",
    "Pet store": "Retail",
    "Pet supply store": "Retail",
    "Pet trainer": "Service",
    "Petroleum products company": "Energy",
    "Pharmaceutical company": "Doctors",
    "Pharmaceutical lab": "Doctors",
    "Pharmaceutical products wholesaler": "Wholesale",
    "Pharmacy": "Retail",
    "Phone repair service": "Service",
    "Photo booth": "Service",
    "Photo lab": "Service",
    "Photo shop": "Retail",
    "Photocopiers supplier": "Retail",
    "Photographer": "Service",
    "Photography service": "Service",
    "Photography studio": "Service",
    "Physiatrist": "Doctors",
    "Physical examination center": "Doctors",
    "Physical fitness program": "Health and Wellness",
    "Physical rehabilitation center": "Doctors",
    "Physical therapist": "Doctors",
    "Physical therapy clinic": "Doctors",
    "Physician assistant": "Doctors",
    "Piano bar": "Entertainment",
    "Piano instructor": "Education",
    "Piano moving service": "Service",
    "Pickleball court": "Recreation",
    "Picnic ground": "Outdoor",
    "Picture frame shop": "Retail",
    "Pie shop": "Retail",
    "Pilates studio": "Health and Wellness",
    "Pipe supplier": "Retail",
    "Pizza delivery": "Food Services",
    "Pizza restaurant": "Restaurant",
    "Pizza takeaway": "Food Services",
    "Place of worship": "Religion",
    "Plant nursery": "Retail",
    "Plastic fabrication company": "Manufacturing",
    "Plastic injection molding service": "Manufacturing",
    "Plastic products supplier": "Retail",
    "Plastic surgeon": "Doctors",
    "Plastic surgery clinic": "Doctors",
    "Playground": "Outdoor",
    "Playground equipment supplier": "Retail",
    "Plaza": "Commercial",
    "Plumber": "Service",
    "Plumbing supply store": "Retail",
    "Plus size clothing store": "Retail",
    "Podiatrist": "Doctors",
    "Poke bar": "Restaurant",
    "Police department": "Government",
    "Police station": "Government",
    "Police supply store": "Retail",
    "Political party office": "Government",
    "Polo club": "Recreation",
    "Pond contractor": "Service",
    "Pool billard club": "Recreation",
    "Pool cleaning service": "Service",
    "Pool hall": "Recreation",
    "Porsche dealer": "Automotive",
    "Port": "Transport",
    "Port authority": "Government",
    "Port operating company": "Business",
    "Portable building manufacturer": "Manufacturing",
    "Portable toilet supplier": "Retail",
    "Portrait studio": "Service",
    "Post office": "Government",
    "Postal code": "Geographical Location",
    "Poster store": "Retail",
    "Poultry farm": "Agriculture",
    "Powder coating service": "Manufacturing",
    "Power plant consultant": "Consulting",
    "Power plant equipment supplier": "Retail",
    "Power station": "Energy",
    "Powersports vehicle dealer": "Automotive",
    "Pregnancy care center": "Doctors",
    "Preparatory school": "Education",
    "Presbyterian church": "Religion",
    "Preschool": "Education",
    "Pressure washing service": "Service",
    "Primary school": "Education",
    "Print shop": "Retail",
    "Printer repair service": "Service",
    "Printing": "Service",
    "Printing equipment supplier": "Retail",
    "Prison": "Government",
    "Private college": "Education",
    "Private educational institution": "Education",
    "Private equity firm": "Business",
    "Private golf course": "Recreation",
    "Private hospital": "Doctors",
    "Private investigator": "Service",
    "Private sector bank": "Finance",
    "Private university": "Education",
    "Probation office": "Government",
    "Process server": "Service",
    "Produce market": "Retail",
    "Produce wholesaler": "Wholesale",
    "Professional and hobby associations": "Organization",
    "Professional association": "Organization",
    "Professional organizer": "Service",
    "Professional services": "Business Services",
    "Promotional products supplier": "Retail",
    "Propane supplier": "Retail",
    "Property investment company": "Business",
    "Property maintenance": "Service",
    "Property management company": "Business",
    "Prosthodontist": "Doctors",
    "Psychiatric hospital": "Doctors",
    "Psychiatrist": "Doctors",
    "Psychic": "Service",
    "Psychologist": "Doctors",
    "Psychotherapist": "Doctors",
    "Pub": "Entertainment",
    "Public bathroom": "Public Services",
    "Public beach": "Outdoor",
    "Public defender's office": "Government",
    "Public educational institution": "Education",
    "Public golf course": "Recreation",
    "Public health department": "Government",
    "Public library": "Public Services",
"Public prosecutors office": "Government",
    "Public relations firm": "Business Services",
    "Public safety office": "Government",
    "Public swimming pool": "Recreation",
    "Public transport": "Transport",
    "Public university": "Education",
    "Public works department": "Government",
    "Publisher": "Business",
    "Puerto Rican restaurant": "Restaurant",
    "Pulmonologist": "Doctors",
    "Pump supplier": "Retail",
    "Quarry": "Mining",
    "Quilt shop": "Retail",
    "Racecourse": "Recreation",
    "Racing car parts store": "Retail",
    "Racquetball club": "Recreation",
    "Radio broadcaster": "Media",
    "Radiologist": "Doctors",
    "Raft trip outfitter": "Recreation",
    "Rafting": "Recreation",
    "Rail museum": "Museum",
    "Railroad company": "Transport",
    "Railroad contractor": "Construction",
    "Railroad equipment supplier": "Retail",
    "Railroad ties supplier": "Retail",
    "Railway services": "Transport",
    "Ram dealer": "Automotive",
    "Ramen restaurant": "Restaurant",
    "Ranch": "Agriculture",
    "Ravine": "Geographical Location",
    "Ready mix concrete supplier": "Retail",
    "Real estate agency": "Business Services",
    "Real estate agent": "Service",
    "Real estate appraiser": "Service",
    "Real estate attorney": "Legal Services",
    "Real estate auctioneer": "Service",
    "Real estate consultant": "Service",
    "Real estate developer": "Business",
    "Real estate rental agency": "Business Services",
    "Record company": "Entertainment",
    "Record store": "Retail",
    "Recording studio": "Service",
    "Records storage facility": "Storage",
    "Recreation": "Recreation",
    "Recreation center": "Recreation",
    "Recreational vehicle rental agency": "Service",
    "Recruiter": "Business Services",
    "Recycling center": "Service",
    "Reef": "Natural Feature",
    "Reflexologist": "Doctors",
    "Reform synagogue": "Religion",
    "Refrigerated transport service": "Transport",
    "Regional airport": "Transport",
    "Regional council": "Government",
    "Registered general nurse": "Doctors",
    "Registration office": "Government",
    "Rehabilitation center": "Doctors",
    "Rehearsal studio": "Entertainment",
    "Reiki therapist": "Doctors",
    "Religious institution": "Religion",
    "Religious organization": "Religion",
    "Religious school": "Education",
    "Remodeler": "Service",
    "Rental": "Service",
    "Rental car return location": "Transport",
    "Renter's insurance agency": "Insurance",
    "Repair service": "Service",
    "Reproductive health clinic": "Doctors",
    "Reptile store": "Retail",
    "Research and product development": "Business",
    "Research engineer": "Business",
    "Research foundation": "Non-profit",
    "Research institute": "Education",
    "Resort hotel": "Hospitality",
    "Rest stop": "Service",
    "Restaurant": "Restaurant",
    "Restaurant supply store": "Retail",
    "Retail space rental agency": "Business Services",
    "Retaining wall supplier": "Retail",
    "Retirement community": "Doctors",
    "Retirement home": "Doctors",
    "Retreat center": "Hospitality",
    "Rheumatologist": "Doctors",
    "Rice mill": "Manufacturing",
    "Rideshare pickup location": "Transport",
    "Ridge": "Geographical Location",
    "River": "Natural Feature",
    "River port": "Transport",
    "Road construction company": "Construction",
    "Road cycling": "Recreation",
    "Roads ports and canals engineers association": "Organization",
    "Rock climbing": "Recreation",
    "Rock climbing gym": "Recreation",
    "Rock climbing instructor": "Service",
    "Rock shop": "Retail",
    "Rodeo": "Recreation",
    "Roller coaster": "Recreation",
    "Roller skating rink": "Recreation",
    "Rolls-Royce dealer": "Automotive",
    "Roofing contractor": "Construction",
    "Roofing supply store": "Retail",
    "Rubber products supplier": "Retail",
    "Running store": "Retail",
    "Russian Orthodox church": "Religion",
    "Russian restaurant": "Restaurant",
    "Rustic furniture store": "Retail",
    "RV dealer": "Automotive",
    "RV park": "Recreation",
    "RV repair shop": "Service",
    "RV storage facility": "Storage",
    "RV supply store": "Retail",
    "Saddlery": "Retail",
    "Safety equipment supplier": "Retail",
    "Sailing club": "Recreation",
    "Sailing school": "Education",
    "Sailmaker": "Retail",
    "Salad shop": "Restaurant",
    "Salvadoran restaurant": "Restaurant",
    "Salvage yard": "Service",
    "Sand & gravel supplier": "Retail",
    "Sandblasting service": "Service",
    "Sandwich shop": "Restaurant",
    "Sanitation service": "Service",
    "Satellite communication service": "Service",
    "Sauna": "Health and Wellness",
    "Sauna store": "Retail",
    "Savings bank": "Finance",
    "Saw mill": "Manufacturing",
    "Scaffolding rental service": "Service",
    "Scale model club": "Hobby",
    "Scale repair service": "Service",
    "Scenic spot": "Outdoor",
    "School": "Education",
    "School administration office": "Education",
    "School bus service": "Transport",
    "School center": "Education",
    "School district office": "Government",
    "School house": "Education",
    "School supply store": "Retail",
    "Science museum": "Museum",
    "Scientific equipment supplier": "Retail",
    "Scooter rental service": "Service",
    "Scooter repair shop": "Service",
    "Scrap metal dealer": "Retail",
    "Screen printer": "Service",
    "Screen printing shop": "Service",
    "Screen repair service": "Service",
    "SCUBA instructor": "Service",
    "Sculpture": "Art",
    "Seafood market": "Retail",
    "Seafood restaurant": "Restaurant",
    "Seafood wholesaler": "Wholesale",
    "Seaplane base": "Transport",
    "Seaport": "Transport",
    "Second hand store": "Retail",
    "Security guard service": "Service",
    "Security service": "Service",
    "Security system installation service": "Service",
    "Security system supplier": "Retail",
    "Self-storage facility": "Storage",
    "Self defense school": "Education",
    "Self service car wash": "Service",
    "Semi conductor supplier": "Retail",
    "Senior citizen center": "Doctors",
    "Septic system service": "Service",
    "Serbian restaurant": "Restaurant",
    "Service establishment": "Service",
    "Services": "Business Services",
    "Sewage treatment plant": "Public Services",
    "Sewing company": "Manufacturing",
    "Sewing shop": "Retail",
    "Shed builder": "Construction",
    "Sheet metal contractor": "Construction",
    "Shelving store": "Retail",
    "Sheriff's department": "Government",
    "Shipbuilding and repair company": "Manufacturing",
    "Shipping and mailing": "Service",
    "Shipping and mailing service": "Service",
    "Shipping company": "Transport",
    "Shipping service": "Service",
    "Shipyard": "Manufacturing",
    "Shoe factory": "Manufacturing",
    "Shoe store": "Retail",
    "Shooting range": "Recreation",
    "Shopping mall": "Retail",
    "Shower door shop": "Retail",
    "Showroom": "Retail",
    "Shredding service": "Service",
    "Shrine": "Religion",
    "Siding contractor": "Construction",
    "Sightseeing tour agency": "Tourism",
    "Sign shop": "Retail",
    "Skate shop": "Retail",
"Skateboard park": "Recreation",
    "Skateboard shop": "Retail",
    "Ski rental service": "Service",
    "Ski repair service": "Service",
    "Ski resort": "Recreation",
    "Ski school": "Education",
    "Ski shop": "Retail",
    "Skin care clinic": "Doctors",
    "Skydiving center": "Recreation",
    "Sleep clinic": "Doctors",
    "Small claims assistance service": "Service",
    "Small engine repair service": "Service",
    "Smog inspection station": "Service",
    "Smoke shop": "Retail",
    "Snack bar": "Restaurant",
    "Snow removal service": "Service",
    "Snowboard shop": "Retail",
    "Snowmobile dealer": "Automotive",
    "Snowmobile rental service": "Service",
    "Soccer club": "Recreation",
    "Soccer field": "Recreation",
    "Soccer practice": "Recreation",
    "Soccer store": "Retail",
    "Social club": "Social",
    "Social security attorney": "Legal Services",
    "Social security office": "Government",
    "Social services organization": "Non-profit",
    "Social welfare center": "Non-profit",
    "Social worker": "Doctors",
    "Sod supplier": "Retail",
    "Soft drinks shop": "Retail",
    "Softball club": "Recreation",
    "Software company": "Business",
    "Soil testing service": "Service",
    "Solar energy company": "Business",
    "Solar energy equipment supplier": "Retail",
    "Solar energy system service": "Service",
    "Solid waste engineer": "Engineering",
    "Soul food restaurant": "Restaurant",
    "Soup kitchen": "Non-profit",
    "Southeast Asian restaurant": "Restaurant",
    "Southern restaurant (US)": "Restaurant",
    "Southwestern restaurant (US)": "Restaurant",
    "Souvenir store": "Retail",
    "Spa": "Health and Wellness",
    "Spa and health club": "Health and Wellness",
    "Spanish restaurant": "Restaurant",
    "Special education school": "Education",
    "Specialized clinic": "Doctors",
    "Specialized hospital": "Doctors",
    "Speech pathologist": "Doctors",
    "Sport tour agency": "Tourism",
    "Sporting goods store": "Retail",
    "Sports accessories wholesaler": "Wholesale",
    "Sports activity location": "Recreation",
    "Sports bar": "Restaurant",
    "Sports card store": "Retail",
    "Sports club": "Recreation",
    "Sports complex": "Recreation",
    "Sports equipment rental service": "Service",
    "Sports massage therapist": "Doctors",
    "Sports medicine clinic": "Doctors",
    "Sports medicine physician": "Doctors",
    "Sports nutrition store": "Retail",
    "Sports school": "Education",
    "Sportswear store": "Retail",
    "Sportwear manufacturer": "Manufacturing",
    "Spring": "Natural Feature",
    "Spring supplier": "Retail",
    "Squash club": "Recreation",
    "Stable": "Recreation",
    "Stadium": "Recreation",
    "Stage": "Entertainment",
    "Stage lighting equipment supplier": "Retail",
    "Stained glass studio": "Art",
    "Stainless steel plant": "Manufacturing",
    "State government office": "Government",
    "State liquor store": "Retail",
    "State park": "Recreation",
    "State police": "Government",
    "Stationery store": "Retail",
    "STD testing service": "Doctors",
    "Steak house": "Restaurant",
    "Steel construction company": "Construction",
    "Steel distributor": "Wholesale",
    "Steel erector": "Construction",
    "Steel fabricator": "Manufacturing",
    "Stock broker": "Finance",
    "Stone supplier": "Retail",
    "Storage": "Storage",
    "Storage facility": "Storage",
    "Store": "Retail",
    "Stores and shopping": "Retail",
    "Structural engineer": "Engineering",
    "Stucco contractor": "Construction",
    "Student career counseling office": "Education",
    "Student dormitory": "Housing",
    "Student housing center": "Housing",
    "Student union": "Education",
    "Students support association": "Non-profit",
    "Study at home school": "Education",
    "Subaru dealer": "Automotive",
    "Suburban train line": "Transport",
    "Subway station": "Transport",
    "Sukiyaki and Shabu Shabu restaurant": "Restaurant",
    "Summer camp organizer": "Recreation",
    "Sunglasses store": "Retail",
    "Supermarket": "Retail",
    "Support group": "Non-profit",
    "Surf lifesaving club": "Recreation",
    "Surf school": "Education",
    "Surf shop": "Retail",
    "Surgeon": "Doctors",
    "Surgical center": "Doctors",
    "Surgical supply store": "Retail",
    "Surplus store": "Retail",
    "Surveyor": "Service",
    "Sushi restaurant": "Restaurant",
    "Sushi takeaway": "Restaurant",
    "Swim club": "Recreation",
    "Swimming": "Recreation",
    "Swimming facility": "Recreation",
    "Swimming instructor": "Service",
    "Swimming lake": "Recreation",
    "Swimming pool": "Recreation",
    "Swimming pool contractor": "Construction",
    "Swimming pool repair service": "Service",
    "Swimming school": "Education",
    "Swimwear store": "Retail",
    "T-shirt store": "Retail",
    "Table tennis supply store": "Retail",
    "Tack shop": "Retail",
    "Taco restaurant": "Restaurant",
    "Taekwondo school": "Education",
    "Tai chi school": "Education",
    "Tailor": "Retail",
    "Takeout restaurant": "Restaurant",
    "Talent agency": "Service",
    "Tanning salon": "Health and Wellness",
    "Tapas bar": "Restaurant",
    "Tattoo and piercing shop": "Retail",
    "Tattoo removal service": "Service",
    "Tattoo shop": "Retail",
    "Tax assessor": "Government",
    "Tax attorney": "Legal Services",
    "Tax collector's office": "Government",
    "Tax consultant": "Service",
    "Tax department": "Government",
    "Tax preparation": "Service",
    "Tax preparation service": "Service",
    "Taxi service": "Transport",
    "Taxi stand": "Transport",
    "Tea house": "Restaurant",
    "Tea manufacturer": "Manufacturing",
    "Tea store": "Retail",
    "Teachers' housing": "Housing",
    "Technical school": "Education",
    "Technical university": "Education",
    "Teeth whitening service": "Doctors",
    "Telecommunications": "Technology",
    "Telecommunications contractor": "Service",
    "Telecommunications engineer": "Technology",
    "Telecommunications equipment supplier": "Retail",
    "Telecommunications service provider": "Service",
    "Telemarketing service": "Service",
    "Telephone company": "Telecommunications",
    "Television station": "Media",
    "Temp agency": "Business Services",
    "Tennis club": "Recreation",
    "Tennis court": "Recreation",
    "Tennis court construction company": "Construction",
    "Tennis instructor": "Service",
    "Tennis store": "Retail",
    "Tent rental service": "Service",
    "Tesla showroom": "Automotive",
    "Test preparation center": "Education",
    "Tex-Mex restaurant": "Restaurant",
    "Textile engineer": "Engineering",
    "Textile mill": "Manufacturing",
    "Thai restaurant": "Restaurant",
    "Theater supply store": "Retail",
    "Theme park": "Recreation",
    "Thrift store": "Retail",
    "Tiki bar": "Restaurant",
    "Tile cleaning service": "Service",
    "Tile contractor": "Construction",
    "Tile store": "Retail",
    "Timeshare agency": "Service",
    "Tire shop": "Retail",
    "Title company": "Business Services",
    "Tobacco shop": "Retail",
    "Toll road rest stop": "Service",
    "Toll station": "Transport",
    "Tool & die shop": "Manufacturing",
    "Tool manufacturer": "Manufacturing",
    "Tool rental service": "Service",
    "Tool store": "Retail",
    "Tortilla shop": "Restaurant",
    "Tour agency": "Tourism",
    "Tour operator": "Tourism",
    "Tourism": "Tourism",
    "Tourist attraction": "Tourism",
    "Tourist information center": "Tourism",
    "Towing equipment provider": "Automotive",
    "Towing service": "Automotive",
    "Townhouse complex": "Housing",
    "Toy store": "Retail",
    "Toyota dealer": "Automotive",
    "Tractor dealer": "Automotive",
    "Tractor repair shop": "Service",
    "Trade school": "Education",
    "Trading card store": "Retail",
    "Traditional American restaurant": "Restaurant",
    "Trailer dealer": "Automotive",
    "Trailer manufacturer": "Manufacturing",
    "Trailer rental service": "Service",
    "Trailer repair shop": "Service",
    "Trailer supply store": "Retail",
    "Train depot": "Transport",
    "Train station": "Transport",
    "Train ticket agency": "Service",
    "Train ticket office": "Transport",
    "Train yard": "Transport",
    "Training centre": "Education",
    "Tram stop": "Transport",
    "Transcription service": "Service",
    "Transit depot": "Transport",
    "Transit station": "Transport",
    "Transit stop": "Transport",
    "Translation service": "Service",
    "Transmission shop": "Automotive",
    "Transport hub": "Transport",
    "Transportation escort service": "Service",
    "Transportation infrastructure": "Transport",
    "Transportation service": "Transport",
    "Travel agency": "Tourism",
    "Travel clinic": "Doctors",
    "Travel lounge": "Travel",
    "Tree service": "Service",
    "Trial attorney": "Legal Services",
    "Tribal headquarters": "Government",
    "Trophy shop": "Retail",
    "Tropical fish store": "Retail",
    "Truck accessories store": "Retail",
    "Truck dealer": "Automotive",
    "Truck driving school": "Education",
    "Truck parts supplier": "Retail",
    "Truck rental agency": "Service",
    "Truck repair shop": "Service",
    "Truck stop": "Transport",
    "Trucking": "Business",
    "Trucking company": "Business",
    "Truss manufacturer": "Manufacturing",
    "Trust bank": "Finance",
    "Turf supplier": "Retail",
    "Tutoring service": "Education",
    "Typing service": "Service",
    "Unemployment office": "Government",
    "Uniform store": "Retail",
    "Unitarian Universalist Church": "Religion",
    "United Methodist church": "Religion",
    "University": "Education",
    "University hospital": "Doctors",
    "University library": "Education",
    "Upholstery shop": "Retail",
    "Urban planning department": "Government",
    "Urgent care center": "Doctors",
    "Urologist": "Doctors",
    "Urology clinic": "Doctors",
    "Used auto parts store": "Retail",
    "Used bicycle shop": "Retail",
    "Used car dealer": "Automotive",
    "Used clothing store": "Retail",
    "Used furniture store": "Retail",
    "Used motorcycle dealer": "Automotive",
    "Used tire shop": "Retail",
    "Used truck dealer": "Automotive",
    "Utility contractor": "Construction",
    "Utility trailer dealer": "Retail",
    "Vacation home rental agency": "Service",
    "Vacuum cleaning system supplier": "Retail",
    "Valet parking service": "Service",
    "Van rental agency": "Service",
    "Vaporizer store": "Retail",
    "Variety store": "Retail",
    "Vascular surgeon": "Doctors",
    "Vegan restaurant": "Restaurant",
    "Vegetarian cafe and deli": "Restaurant",
    "Vegetarian restaurant": "Restaurant",
    "Vehicle exporter": "Business",
    "Vehicle inspection service": "Service",
    "Vehicle shipping agent": "Service",
    "Vehicle wrapping service": "Service",
    "Velodrome": "Recreation",
    "Vending machine supplier": "Retail",
    "Venezuelan restaurant": "Restaurant",
    "Venture capital company": "Finance",
    "Veterans affairs department": "Government",
    "Veterans center": "Non-profit",
    "Veterans hospital": "Doctors",
    "Veterans organization": "Non-profit",
    "Veterinarian": "Doctors",
    "Veterinary care": "Doctors",
    "Veterinary pharmacy": "Retail",
    "Video arcade": "Entertainment",
    "Video editing service": "Service",
    "Video game rental store": "Retail",
    "Video game store": "Retail",
    "Video karaoke": "Entertainment",
    "Video production service": "Service",
    "Vietnamese restaurant": "Restaurant",
    "Vineyard": "Business",
    "Vintage clothing store": "Retail",
    "Vinyl sign shop": "Retail",
    "Visa consulting service": "Service",
    "Visitor center": "Tourism",
    "Vista point": "Recreation",
    "Vitamin & supplements store": "Retail",
    "Vocational school": "Education",
    "Vocational secondary school": "Education",
    "Volcano": "Natural Feature",
    "Volkswagen dealer": "Automotive",
    "Volleyball club": "Recreation",
    "Volunteer organization": "Non-profit",
    "Volvo dealer": "Automotive",
    "Walk-in clinic": "Doctors",
    "Wallpaper installer": "Service",
    "Wallpaper store": "Retail",
    "War memorial": "Cultural",
    "War museum": "Cultural",
    "Warehouse": "Business",
    "Warehouse club": "Retail",
    "Warehouse store": "Retail",
    "Waste management service": "Service",
    "Watch store": "Retail",
    "Water damage restoration service": "Service",
    "Water filter supplier": "Retail",
    "Water park": "Recreation",
    "Water purification company": "Business",
    "Water softening equipment supplier": "Retail",
    "Water sports equipment rental service": "Service",
    "Water testing service": "Service",
    "Water treatment plant": "Service",
    "Water treatment supplier": "Retail",
    "Water utility company": "Utility",
    "Water works equipment supplier": "Retail",
    "Waterproofing service": "Service",
    "Waxing hair removal service": "Service",
    "Weather forecast service": "Service",
    "Web hosting company": "Technology",
    "Website designer": "Service",
    "Wedding chapel": "Event",
    "Wedding photographer": "Service",
    "Wedding planner": "Service",
    "Wedding service": "Service",
    "Wedding venue": "Event",
    "Weigh station": "Transport",
    "Weight loss service": "Health and Wellness",
    "Weightlifting area": "Recreation",
    "Weir": "Natural Feature",
    "Welder": "Service",
    "Welding supply store": "Retail",
    "Well drilling contractor": "Service",
    "Wellness center": "Health and Wellness",
    "Wellness program": "Health and Wellness",
    "Western apparel store": "Retail",
    "Western restaurant": "Restaurant",
    "Wetland": "Natural Feature",
    "Whale watching tour agency": "Tourism",
    "Wheel store": "Retail",
    "Wheelchair rental service": "Service",
    "Wheelchair store": "Retail",
    "Wholesale bakery": "Wholesale",
    "Wholesale florist": "Wholesale",
    "Wholesale grocer": "Wholesale",
    "Wholesale plant nursery": "Wholesale",
    "Wholesaler": "Wholesale",
    "Wig shop": "Retail",
    "Wildlife and safari park": "Recreation",
    "Wildlife park": "Recreation",
    "Wildlife refuge": "Natural Feature",
    "Wildlife rescue service": "Service",
    "Window cleaning service": "Service",
    "Window installation service": "Service",
    "Window supplier": "Retail",
    "Window tinting service": "Service",
    "Window treatment store": "Retail",
    "Wine bar": "Restaurant",
    "Wine cellar": "Retail",
    "Wine club": "Retail",
    "Wine store": "Retail",
    "Wine wholesaler and importer": "Wholesale",
    "Winery": "Business",
    "Wing chun school": "Education",
    "Women's clothing store": "Retail",
    "Women's health clinic": "Doctors",
    "Women's organization": "Non-profit",
    "Women's personal trainer": "Health and Wellness",
    "Wood supplier": "Retail",
    "Woods": "Natural Feature",
    "Woodworker": "Service",
    "Woodworking supply store": "Retail",
    "Work clothes store": "Retail",
    "Wrestling school": "Education",
    "Yacht club": "Recreation",
    "Yamaha motorcycle dealer": "Automotive",
    "Yoga instructor": "Health and Wellness",
    "Yoga retreat center": "Health and Wellness",
    "Yoga studio": "Health and Wellness",
    "Youth center": "Youth",
    "Youth club": "Youth",
    "Youth organization": "Youth",
    "Youth social services organization": "Youth",
    "Zoo": "Recreation"
}

pprint(place_types)

csv_file = "place_types.csv"

# Открываем файл для записи в режиме 'w'
with open(csv_file, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)

    # Записываем заголовки
    writer.writerow(["Key", "Value"])

    # Записываем данные из словаря
    for key, value in place_types.items():
        writer.writerow([key, value])

print(f"Словарь успешно сохранен в файл {csv_file}")