# Generated by Django 5.1.7 on 2025-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rating'),
        ),
    ]
