# Generated by Django 5.1.7 on 2025-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_place_num_reviews_alter_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.CharField(blank=True, default=0, max_length=250, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.CharField(blank=True, default=0, max_length=250, verbose_name='Rating'),
        ),
    ]
