# Generated by Django 5.1.8 on 2025-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_place_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
