# Generated by Django 5.1.8 on 2025-04-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_place_num_reviews_alter_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='YouTube'),
        ),
    ]
