# Generated by Django 5.1.8 on 2025-04-03 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_place_address_alter_place_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
