# Generated by Django 5.1.6 on 2025-04-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_place_facebook_alter_place_instagram_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_categor_ea9e99_idx',
            old_name='main_app_pl_categor_cc633a_idx',
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
