# Generated by Django 5.1.6 on 2025-04-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_main_app_pl_categor_cc633a_idx_main_app_pl_categor_ea9e99_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_city_8bd0a3_idx',
            old_name='main_app_pl_city_id_69369b_idx',
        ),
        migrations.AddField(
            model_name='place',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
