# Generated by Django 5.1.6 on 2025-04-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_main_app_pl_city_id_69369b_idx_main_app_pl_city_8bd0a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
