# Generated by Django 5.1.6 on 2025-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_place_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
