# Generated by Django 5.1.6 on 2025-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_place_num_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='clear_website',
            field=models.CharField(max_length=2000, null=True, verbose_name='Website Domain'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='keyword',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=1000, null=True, unique=True, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.CharField(max_length=250, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_24_7',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Open 24/7'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_hours',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(max_length=250, null=True, verbose_name='Type of Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('pending', 'Pending')], default='unpublished', max_length=25, verbose_name='Publication Status'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
