# Generated by Django 5.1.6 on 2025-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_place_facebook_alter_place_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='clear_website',
            field=models.CharField(max_length=1024, null=True, verbose_name='Website Domain'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='located_in',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Located In'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Type of Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('pending', 'Pending')], default='unpublished', max_length=1024, verbose_name='Publication Status'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
