# Generated by Django 5.1.6 on 2025-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_main_app_pl_city_8bd0a3_idx_main_app_pl_city_id_69369b_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_city_8bd0a3_idx',
            old_name='main_app_pl_city_id_69369b_idx',
        ),
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_categor_ea9e99_idx',
            old_name='main_app_pl_categor_cc633a_idx',
        ),
        migrations.AddField(
            model_name='place',
            name='keyword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='status_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=250, verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=2048, null=True, unique=True, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='YouTube'),
        ),
    ]
