# Generated by Django 5.1.6 on 2025-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_main_app_pl_city_id_69369b_idx_main_app_pl_city_8bd0a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
