# Generated by Django 5.1.6 on 2025-04-04 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_place_open_24_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.CharField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.CharField(blank=True, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.CharField(blank=True, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
