# Generated by Django 5.1.6 on 2025-04-04 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_place_facebook_alter_place_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.TextField(verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='clear_website',
            field=models.TextField(max_length=250, null=True, verbose_name='Website Domain'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.TextField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.TextField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='located_in',
            field=models.TextField(blank=True, null=True, verbose_name='Located In'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.TextField(max_length=100, null=True, verbose_name='Type of Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.TextField(blank=True, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Place Slug'),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
