# Generated by Django 5.1.6 on 2025-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_place_address_alter_place_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
