# Generated by Django 5.1.6 on 2025-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_place_status_review_alter_place_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='open_24_7',
            field=models.TextField(default='No', verbose_name='Open 24/7'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.TextField(null=True, verbose_name='Type of Place'),
        ),
    ]
