# Generated by Django 5.1.6 on 2025-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_place_open_24_7_alter_place_open_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='clear_website',
            field=models.TextField(null=True, verbose_name='Website Domain'),
        ),
    ]
