# Generated by Django 5.1.6 on 2025-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_place_clear_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Place Slug'),
        ),
    ]
