# Generated by Django 5.1.6 on 2025-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Email Address'),
        ),
    ]
