# Generated by Django 5.1.6 on 2025-04-04 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_place_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website'),
        ),
    ]
