# Generated by Django 5.1.6 on 2025-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_place_email_alter_place_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.TextField(null=True, verbose_name='Google Maps Link'),
        ),
    ]
