# Generated by Django 5.1.6 on 2025-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_alter_place_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='Place Slug'),
        ),
    ]
