# Generated by Django 5.1.6 on 2025-04-04 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_alter_place_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_city_id_69369b_idx',
            old_name='main_app_pl_city_8bd0a3_idx',
        ),
        migrations.RenameIndex(
            model_name='place',
            new_name='main_app_pl_categor_cc633a_idx',
            old_name='main_app_pl_categor_ea9e99_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='status_review',
        ),
        migrations.RemoveField(
            model_name='place',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='main_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='main_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='clear_website',
            field=models.CharField(max_length=250, null=True, verbose_name='Website Domain'),
        ),
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=1024, null=True, unique=True, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='located_in',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Located In'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_24_7',
            field=models.BooleanField(default=False, verbose_name='Open 24/7'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_hours',
            field=models.CharField(blank=True, null=True, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Type of Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Place Slug'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='YouTube'),
        ),
    ]
