# Generated by Django 5.1.6 on 2025-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_rename_main_app_pl_city_8bd0a3_idx_main_app_pl_city_id_69369b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=10000, null=True, unique=True, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='YouTube'),
        ),
    ]
