# Generated by Django 5.1.6 on 2025-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_alter_place_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=10000, null=True, verbose_name='Google Maps Link'),
        ),
    ]
